name: saleplants
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.0.6+1
  flutter_modular: ^4.5.1+1
  doc_widget: ^0.2.8
  sizer: ^2.0.15


  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

scripts:
  build: flutter pub run build_runner build --delete-conflicting-outputs
  watch: flutter pub run build_runner watch --delete-conflicting-outputs
